version: '3.8'

services:
  dagster:
    build: .
    environment:
      - DAGSTER_HOME=/opt/dagster/dagster_home
      - PYTHONPATH=/opt/dagster/app
    volumes:
      - .:/opt/dagster/app
    ports:
      - "3000:3000"
    working_dir: /opt/dagster/app
    command: dagster dev -h 0.0.0.0 -p 3000
